export const coursesData = [
    {
      "name": "Γραμμική Άλγεβρα",
      "code": "Κ03",
      "ECTS": 6,
      "category": "ΥΜ",
      "semester": 1,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Διακριτά Μαθηματικά",
      "code": "Κ09",
      "ECTS": 7,
      "category": "ΥΜ",
      "semester": 1,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Εισαγωγή στην Πληροφορική και στις Τηλεπικοινωνίες",
      "code": "ΓΠ07",
      "ECTS": 2,
      "category": "ΓΠ",
      "semester": 1,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Εισαγωγή στον Προγραμματισμό",
      "code": "Κ04",
      "ECTS": 7,
      "category": "ΥΜ",
      "semester": 1,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Εργαστήριο Λογικής Σχεδίασης",
      "code": "K02ε",
      "ECTS": 2,
      "category": "ΕΡ",
      "semester": 1,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Λογική Σχεδίαση",
      "code": "Κ02",
      "ECTS": 6,
      "category": "ΥΜ",
      "semester": 1,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Ανάλυση Ι",
      "code": "Κ01",
      "ECTS": 8,
      "category": "ΥΜ",
      "semester": 2,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Αρχιτεκτονική Υπολογιστών Ι",
      "code": "Κ14",
      "ECTS": 7,
      "category": "ΥΜ",
      "semester": 2,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Δομές Δεδομένων και Τεχνικές Προγραμματισμού",
      "code": "Κ08",
      "ECTS": 7,
      "category": "ΥΜ",
      "semester": 2,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Εφαρμοσμένα Μαθηματικά",
      "code": "Κ20β",
      "ECTS": 6,
      "category": "ΠΜ",
      "semester": 2,
      "s6": "B",
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Ηλεκτρομαγνητισμός – Οπτική και Σύγχρονη Φυσική",
      "code": "Κ12",
      "ECTS": 8,
      "category": "ΥΜ",
      "semester": 2,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Ανάλυση ΙΙ",
      "code": "Κ06",
      "ECTS": 8,
      "category": "ΥΜ",
      "semester": 3,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Αντικειμενοστραφής Προγραμματισμός",
      "code": "Κ10",
      "ECTS": 8,
      "category": "ΥΜ",
      "semester": 3,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Εργαστήριο Κυκλωμάτων και Συστημάτων",
      "code": "Κ11ε",
      "ECTS": 2,
      "category": "ΕΡ",
      "semester": 3,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Πιθανότητες και Στατιστική",
      "code": "Κ13",
      "ECTS": 6,
      "category": "ΥΜ",
      "semester": 3,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Σήματα και Συστήματα",
      "code": "Κ11",
      "ECTS": 6,
      "category": "ΥΜ",
      "semester": 3,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Αλγόριθμοι και Πολυπλοκότητα",
      "code": "Κ17",
      "ECTS": 8,
      "category": "ΥΜ",
      "semester": 4,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Δίκτυα Επικοινωνιών I",
      "code": "Κ16",
      "ECTS": 6,
      "category": "ΥΜ",
      "semester": 4,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Εργαστήριο Δικτύων Επικοινωνιών Ι",
      "code": "Κ16ε",
      "ECTS": 2,
      "category": "ΕΡ",
      "semester": 4,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Συστήματα Επικοινωνιών",
      "code": "Κ21",
      "ECTS": 7,
      "category": "ΥΜ",
      "semester": 4,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Σχεδίαση και Χρήση Βάσεων Δεδομένων",
      "code": "Κ29",
      "ECTS": 7,
      "category": "ΥΜ",
      "semester": 4,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Αριθμητική Ανάλυση",
      "code": "Κ15",
      "ECTS": 6,
      "category": "ΕΥΜ",
      "semester": 5,
      "s1": "Υ",
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Αρχές Γλωσσών Προγραμματισμού",
      "code": "ΘΠ01",
      "ECTS": 6,
      "category": "ΠΜ",
      "semester": 5,
      "s2": "B",
      "s3": "B",
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Αρχιτεκτονική Υπολογιστών ΙΙ",
      "code": "Κ30",
      "ECTS": 6,
      "category": "ΕΥΜ",
      "semester": 5,
      "s5": "B",
      "s6": "Υ",
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Γραφικά Ι",
      "code": "ΘΠ02",
      "ECTS": 6,
      "category": "ΠΜ",
      "semester": 5,
      "s1": "B",
      "s5": "B",
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Δίκτυα Επικοινωνιών II",
      "code": "Κ33",
      "ECTS": 6,
      "category": "ΕΥΜ",
      "semester": 5,
      "s6": "Υ",
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Λειτουργικά Συστήματα",
      "code": "Κ22",
      "ECTS": 8,
      "category": "ΥΜ",
      "semester": 5,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Παράλληλα Συστήματα",
      "code": "ΘΠ04",
      "ECTS": 6,
      "category": "ΠΜ",
      "semester": 5,
      "s4": "B",
      "s5": "B",
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Σχεδίαση Ψηφιακών Συστημάτων - VHDL",
      "code": "ΥΣ03",
      "ECTS": 6,
      "category": "ΠΜ",
      "semester": 5,
      "s5": "B",
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Τεχνητή Νοημοσύνη I",
      "code": "ΥΣ02",
      "ECTS": 6,
      "category": "ΠΜ",
      "semester": 5,
      "s2": "B",
      "s3": "B",
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Τηλεπικοινωνιακά Δίκτυα",
      "code": "ΕΠ20",
      "ECTS": 6,
      "category": "ΠΜ",
      "semester": 5,
      "s5": "B",
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Υλοποίηση Συστημάτων Βάσεων Δεδομένων",
      "code": "Κ18",
      "ECTS": 6,
      "category": "ΕΥΜ",
      "semester": 5,
      "s2": "Υ",
      "s3": "Υ",
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Ψηφιακή Επεξεργασία Σήματος",
      "code": "Κ32",
      "ECTS": 6,
      "category": "ΕΥΜ",
      "semester": 5,
      "s6": "Υ",
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Αναγνώριση Προτύπων – Μηχανική Μάθηση",
      "code": "ΕΠ08",
      "ECTS": 6,
      "category": "ΠΜ",
      "semester": 6,
      "s1": "B",
      "s2": "B",
      "s5": "B",
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Ανάλυση/Σχεδίαση Συστημάτων Λογισμικού",
      "code": "ΥΣ04",
      "ECTS": 6,
      "category": "ΠΜ",
      "semester": 6,
      "s4": "B",
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Ασύρματα Δίκτυα Αισθητήρων",
      "code": "ΥΣ18",
      "ECTS": 6,
      "category": "ΠΜ",
      "semester": 6,
      "s5": "B",
      "s6": "B",
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Διαχείριση Δικτύων",
      "code": "Κ34",
      "ECTS": 6,
      "category": "ΕΥΜ",
      "semester": 6,
      "s6": "Υ",
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Επεξεργασία Στοχαστικών Σημάτων",
      "code": "ΕΠ07",
      "ECTS": 6,
      "category": "ΠΜ",
      "semester": 6,
      "s5": "B",
      "s6": "B",
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Επιστημονικοί Υπολογισμοί",
      "code": "ΘΠ03",
      "ECTS": 6,
      "category": "ΠΜ",
      "semester": 6,
      "s1": "B",
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Εργαστήριο Ηλεκτρονικής",
      "code": "Κ19ε",
      "ECTS": 6,
      "category": "ΠΜ",
      "semester": 6,
      "s5": "B",
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Ηλεκτρονική",
      "code": "K19",
      "ECTS": 6,
      "category": "ΕΥΜ",
      "semester": 6,
      "s6": "Υ",
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Θεωρία Πληροφορίας και Κωδίκων",
      "code": "Κ35",
      "ECTS": 6,
      "category": "ΕΥΜ",
      "semester": 6,
      "s6": "Υ",
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Θεωρία Υπολογισμού",
      "code": "Κ25",
      "ECTS": 6,
      "category": "ΕΥΜ",
      "semester": 6,
      "s2": "Υ",
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Λογικός Προγραμματισμός",
      "code": "ΥΣ05",
      "ECTS": 6,
      "category": "ΠΜ",
      "semester": 6,
      "s1": "B",
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Μαθηματικά Πληροφορικής",
      "code": "Κ20α",
      "ECTS": 6,
      "category": "ΕΥΜ",
      "semester": 6,
      "s1": "Υ",
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Μεταγλωττιστές",
      "code": "Κ31",
      "ECTS": 6,
      "category": "ΕΥΜ",
      "semester": 6,
      "s3": "Υ",
      "s5": "B",
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Προγραμματισμός Συστήματος",
      "code": "Κ24",
      "ECTS": 8,
      "category": "ΥΜ",
      "semester": 6,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Τεχνητή Νοημοσύνη ΙΙ (Βαθιά Μηχανική Μάθηση για την Επεξεργασία Φυσικής Γλώσσας)",
      "code": "ΥΣ19",
      "ECTS": 6,
      "category": "ΠΜ",
      "semester": 6,
      "s2": "B",
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Τεχνικές Εξόρυξης Δεδομένων",
      "code": "ΥΣ11",
      "ECTS": 6,
      "category": "ΠΜ",
      "semester": 6,
      "s2": "B",
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Τεχνολογίες Εφαρμογών Διαδικτύου",
      "code": "ΥΣ14",
      "ECTS": 6,
      "category": "ΠΜ",
      "semester": 6,
      "s5": "B",
      "s6": "B",
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Αλγοριθμική Επιχειρησιακή Έρευνα",
      "code": "ΘΠ09",
      "ECTS": 6,
      "category": "ΠΜ",
      "semester": 7,
      "s1": "B",
      "s2": "B",
      "s5": "B",
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Ανάπτυξη Λογισμικού για Αλγοριθμικά Προβλήματα",
      "code": "Κ23γ",
      "ECTS": 8,
      "category": "Project",
      "semester": 7,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Ανάπτυξη Λογισμικού για Πληροφοριακά Συστήματα",
      "code": "Κ23α",
      "ECTS": 8,
      "category": "Project",
      "semester": 7,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Ανάπτυξη Λογισμικού για Συστήματα Δικτύων και Τηλεπικοινωνιών",
      "code": "Κ23β",
      "ECTS": 8,
      "category": "Project",
      "semester": 7,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Διδακτική της Πληροφορικής",
      "code": "ΥΣ10",
      "ECTS": 6,
      "category": "ΠΜ",
      "semester": 7,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Δομή και Θεσμοί της Ευρωπαϊκής Ένωσης",
      "code": "ΓΠ03",
      "ECTS": 2,
      "category": "ΓΠ",
      "semester": 7,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Ειδικά Θέματα Επικοινωνιών και Επεξεργασίας Σήματος: Ειδικά Θέματα Κβαντικής Πληροφορίας και Υπολογιστικής",
      "code": "ΕΠ22δ",
      "ECTS": 4,
      "category": "ΠΜ",
      "semester": 7,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Ειδικά Θέματα Υπολογιστικών Συστημάτων και Εφαρμογών",
      "code": "ΥΣ16",
      "ECTS": 4,
      "category": "ΠΜ",
      "semester": 7,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Ειδικά Θέματα Υπολογιστικών Συστημάτων και Εφαρμογών – Τεχνολογίες Γνώσεων",
      "code": "ΥΣ16β",
      "ECTS": 4,
      "category": "ΠΜ",
      "semester": 7,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Ενισχυτική Μηχανική Μάθηση και Στοχαστικά Παίγνια",
      "code": "ΕΠ22α",
      "ECTS": 6,
      "category": "ΠΜ",
      "semester": 7,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Επικοινωνία Ανθρώπου Μηχανής",
      "code": "ΥΣ08",
      "ECTS": 6,
      "category": "ΠΜ",
      "semester": 7,
      "s1": "B",
      "s2": "B",
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Ηλεκτρονική Διακυβέρνηση",
      "code": "ΥΣ17",
      "ECTS": 4,
      "category": "ΠΜ",
      "semester": 7,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Θεωρία Αριθμών",
      "code": "ΘΠ08",
      "ECTS": 6,
      "category": "ΠΜ",
      "semester": 7,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Οπτικές Επικοινωνίες και Οπτικά Δίκτυα",
      "code": "ΕΠ16",
      "ECTS": 6,
      "category": "ΠΜ",
      "semester": 7,
      "s5": "B",
      "s6": "B",
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Πληροφοριακά Συστήματα",
      "code": "ΥΣ07",
      "ECTS": 6,
      "category": "ΠΜ",
      "semester": 7,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Προηγμένα Θέματα Αλγορίθμων",
      "code": "ΘΠ12",
      "ECTS": 6,
      "category": "ΠΜ",
      "semester": 7,
      "s1": "B",
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Προηγμένοι Επιστημονικοί Υπολογισμοί",
      "code": "ΘΠ18",
      "ECTS": 6,
      "category": "ΠΜ",
      "semester": 7,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Συστήματα Κινητών και Προσωπικών Επικοινωνιών",
      "code": "ΕΠ18",
      "ECTS": 6,
      "category": "ΠΜ",
      "semester": 7,
      "s5": "B",
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Συστήματα Ψηφιακής Επεξεργασίας Σημάτων σε Πραγματικό Χρόνο",
      "code": "ΕΠ11",
      "ECTS": 6,
      "category": "ΠΜ",
      "semester": 7,
      "s5": "B",
      "s6": "B",
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Σχεδίαση VLSI Κυκλωμάτων",
      "code": "ΕΠ01",
      "ECTS": 6,
      "category": "ΠΜ",
      "semester": 7,
      "s5": "B",
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Τεχνολογίες της Πληροφορίας και των Επικοινωνιών (ΤΠΕ) στη Μάθηση",
      "code": "ΥΣ15",
      "ECTS": 6,
      "category": "ΠΜ",
      "semester": 7,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Υπολογιστική Πολυπλοκότητα",
      "code": "ΘΠ20",
      "ECTS": 6,
      "category": "ΠΜ",
      "semester": 7,
      "s1": "B",
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Ψηφιακές Επικοινωνίες",
      "code": "ΕΠ04",
      "ECTS": 6,
      "category": "ΠΜ",
      "semester": 7,
      "s5": "B",
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Ψηφιακή Προσβασιμότητα και Υποστηρικτικές Τεχνολογίες Πληροφορικής",
      "code": "ΥΣ22",
      "ECTS": 6,
      "category": "ΠΜ",
      "semester": 7,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Αλγοριθμική Επίλυση Προβλημάτων",
      "code": "ΘΠ24",
      "ECTS": 6,
      "category": "ΠΜ",
      "semester": 8,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Ανάπτυξη Υλικού-Λογισμικού για Ενσωματωμένα Συστήματα",
      "code": "Κ23δ",
      "ECTS": 8,
      "category": "Project",
      "semester": 8,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Ασύρματες Ζεύξεις",
      "code": "ΕΠ13",
      "ECTS": 6,
      "category": "ΠΜ",
      "semester": 8,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Διοίκηση Έργων και Τεχνικές Παρουσίασης και Συγγραφής Επιστημονικών Εκθέσεων",
      "code": "ΓΠ05",
      "ECTS": 2,
      "category": "ΓΠ",
      "semester": 8,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Ειδικά Θέματα Επικοινωνιών και Επεξεργασίας Σήματος: Γραμμές μεταφοράς, κυματοδηγοί και οπτικές ίνες",
      "code": "ΕΠ22γ",
      "ECTS": 4,
      "category": "ΠΜ",
      "semester": 8,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Ειδικά Θέματα Επικοινωνιών και Επεξεργασίας Σήματος: Ειδικά Θέματα Κβαντικής Μηχανικής Μάθησης",
      "code": "ΕΠ22γ",
      "ECTS": 4,
      "category": "ΠΜ",
      "semester": 8,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Ειδικά Θέματα Θεωρητικής Πληροφορικής: Αλγόριθμοι Δομικής Βιοπληροφορικής",
      "code": "ΘΠ16δ",
      "ECTS": 6,
      "category": "ΠΜ",
      "semester": 8,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Ειδικά Θέματα Υπολογιστικών Συστημάτων και Εφαρμογών",
      "code": "ΥΣ16",
      "ECTS": 4,
      "category": "ΠΜ",
      "semester": 8,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Ειδικά Θέματα Υπολογιστικών Συστημάτων και Εφαρμογών: Υπολογιστικά Συστήματα Μεγάλης Κλίμακας",
      "code": "ΥΣ16α",
      "ECTS": 4,
      "category": "ΠΜ",
      "semester": 8,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Επεξεργασία Εικόνας",
      "code": "ΕΠ10",
      "ECTS": 6,
      "category": "ΠΜ",
      "semester": 8,
      "s5": "B",
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Επεξεργασία Ομιλίας και Φυσικής Γλώσσας",
      "code": "ΕΠ19",
      "ECTS": 6,
      "category": "ΠΜ",
      "semester": 8,
      "s5": "B",
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Επεξεργασία Στοχαστικών Σημάτων",
      "code": "ΕΠ07",
      "ECTS": 6,
      "category": "ΠΜ",
      "semester": 8,
      "s5": "B",
      "s6": "B",
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Θεωρία Γραφημάτων",
      "code": "ΘΠ10",
      "ECTS": 6,
      "category": "ΠΜ",
      "semester": 8,
      "s1": "B",
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Ιστορία της Πληροφορικής και των Τηλεπικοινωνιών",
      "code": "ΥΣ20",
      "ECTS": 4,
      "category": "ΠΜ",
      "semester": 8,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Καινοτομία και Επιχειρηματικότητα",
      "code": "ΥΣ12",
      "ECTS": 4,
      "category": "ΠΜ",
      "semester": 8,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Κρυπτογραφία",
      "code": "ΘΠ05",
      "ECTS": 6,
      "category": "ΠΜ",
      "semester": 8,
      "s1": "B",
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Μικροοικονομική Ανάλυση",
      "code": "ΕΠ24",
      "ECTS": 4,
      "category": "ΠΜ",
      "semester": 8,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Μουσική Πληροφορική",
      "code": "ΕΠ21",
      "ECTS": 4,
      "category": "ΠΜ",
      "semester": 8,
      "s5": "B",
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Παράλληλοι Αλγόριθμοι",
      "code": "ΘΠ19",
      "ECTS": 6,
      "category": "ΠΜ",
      "semester": 8,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Προστασία και Ασφάλεια Υπολογιστικών Συστημάτων",
      "code": "ΥΣ13",
      "ECTS": 6,
      "category": "ΠΜ",
      "semester": 8,
      "s4": "B",
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Σημασιολογία Γλωσσών Προγραμματισμού",
      "code": "ΘΠ16α",
      "ECTS": 6,
      "category": "ΠΜ",
      "semester": 8,
      "s1": "B",
      "s2": "B",
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Σχολική Τάξη & Μικροδιδασκαλία",
      "code": "ΥΣ21",
      "ECTS": 6,
      "category": "ΠΜ",
      "semester": 8,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Τεχνολογία Λογισμικού",
      "code": "ΥΣ09",
      "ECTS": 6,
      "category": "ΠΜ",
      "semester": 8,
      "s4": "B",
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Υπολογιστική Γεωμετρία",
      "code": "ΘΠ11",
      "ECTS": 6,
      "category": "ΠΜ",
      "semester": 8,
      "s1": "B",
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Υπολογιστική Θεωρία Μηχανικής Μάθησης",
      "code": "ΘΠ23",
      "ECTS": 6,
      "category": "ΠΜ",
      "semester": 8,
      "s1": "B",
      "s2": "B",
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Φωτονική",
      "code": "ΕΠ12",
      "ECTS": 6,
      "category": "ΠΜ",
      "semester": 8,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Πτυχιακή 1",
      "code": "ΠΤ1",
      "ECTS": 8,
      "category": "ΠΤ",
      "semester": 8,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Πτυχιακή 2",
      "code": "ΠΤ2",
      "ECTS": 8,
      "category": "ΠΤ",
      "semester": 8,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Πρακτική 1",
      "code": "ΠΡ1",
      "ECTS": 8,
      "category": "ΠΡ",
      "semester": 8,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    },
    {
      "name": "Πρακτική 2",
      "code": "ΠΡ2",
      "ECTS": 8,
      "category": "ΠΡ",
      "semester": 8,
      "grade": 0,
      "hasCourse": false,
      "isActive": false
    }
  ];